version: '3.8'

services:
  rust-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      #- .:/usr/local/bin
      - ../data/models:/app/models
    command: ["image2nord"]
    restart: "unless-stopped"
    # platform: linux/amd64
